### ISSUE TITLE
Allow providing of DOM / jQuery object for subject / targets

### ISSUE THREAD

**Issue by DanielApt** [fortesinformatica/Sideshow#12]
Instead of using a selector string, it's nice to use jQuery / DOM reference.

So in a step it would be:
```js
{
    subject: $('.container').not('.foo')
}
```

**Comment by alcidesqueiroz** [comment]
Assigning a jQuery wrapped object already works for specifying a subject, exactly the way you suggested. It's another option for subject definition, but not really a replacement for the string selector. The reason we've chosen to use a jQuery string selector (allowing the use of [jQuery extended selectors](http://api.jquery.com/category/selectors/jquery-selector-extensions/) too) is that this way the subject is queried on demand, at the beginning of each step. Sometimes, you simply can't select an element in advance, just because it's not rendered yet. The code sample you've posted already works, but with **one condition**: at the moment of tutorial's definition, the jQuery expresion `$('.container').not('.foo')` must return at least (and only) one element reference.
As this feature already exists, I'm closing this issue. Ok? =)
